"firefox" = "ï‰©"
"gcr-prompter" = "ï‚œ"
"gthumb" = "ï€¾"
"Heroic Games Launcher" = "ï„›"
"jellyfin media player" = "ó°¿"
"jetbrains-datagrip" = "ï‘²"
"jetbrains-idea" = "îµ"
"jetbrains-pycharm" = "îœ¼"
"jetbrains-rider" = "ó°ª®"
"jetbrains-rustrover" = "î¨"
"jetbrains-webstorm" = "ó°›¦"
"keepassxc" = "ï‚„"
"kitty" = "ï„ "
"libreoffice" = "ï€µ"
"libreoffice calc" = "ïƒ"
"libreoffice-writer" = "ï…œ"
"nm-connection-editor" = "ï‚­"
"nvim" = "îŸ…"
"nwg-displays" = "ó°º"
"org.remmina.remmina" = "ó°¢¹"
"pavucontrol" = "ï‡"
"rawtherapee" = "ó°„„"
"signal" = "ó°­¹"
"spotify" = "ï†¼"
"udiskie" = "ó°‰"
"wireshark-gtk" = "ïƒ¨"
"zathura" = "î««"
"zoom" = "î«™"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
separator = ": "
